### PR TITLE
Oscar

### PR DESCRIPTION
**Pull request by omathot**
just added env

### CODE REVIEW

**Comment by omathot** [comment]
Make sure there's a new util.c file and a long ass comment in pipe.c explaining some logic, otherwise it means I'm merging the wrong thing cause I'm dumb and then deny it.
The minishell.h conflict is stupid just accept the one with my name on it who's marvin lol

**Comment by P1tayaa** [comment]
Ca a l'ai bon, mais je vais pas te mantir je te fait confience

**Review by P1tayaa — COMMENTED** [review]
Ca a l'ai bon, mais je vais pas te mantir je te fait confience

**Review by P1tayaa — APPROVED** [review]
Ca a l'ai bon, mais je vais pas te mantir je te fait confience

**Pull request merged**
